# Generated by Django 6.0.5 on 2026-05-18 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only english lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
    ]
