# Generated by Django 6.0.5 on 2026-07-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_title'),
        ('projects', '0006_project_skill_level_alter_project_status_milestone'),
    ]

    operations = [
    ]
