# Generated by Django 6.0.5 on 2026-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
