# Generated by Django 6.0.5 on 2026-07-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='employer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bid',
            name='employer_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='experience_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='expert_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='price_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='score_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bid',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='scored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
