# Generated by Django 6.0.5 on 2026-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expret',
            field=models.BooleanField(default=False),
        ),
    ]
