# Generated by Django 6.0.5 on 2026-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_expret'),
        ('categories', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_expret',
            new_name='is_expert',
        ),
        migrations.AddField(
            model_name='user',
            name='expert_categories',
            field=models.ManyToManyField(blank=True, related_name='experts', to='categories.category'),
        ),
    ]
